#!/usr/bin/env python3
"""
mkpsgtab.py - VERA PSG frequency tables for vera-tests/rmt/psgrmt.s

    python3 mkpsgtab.py psgtab.s

VERA PSG frequency word (16 bit):  f = word * (25 MHz / 512) / 2^17
so  word = f * 2^17 * 512 / 25e6 = f * 2.68435456.

A POKEY channel whose divider is n machine cycles gives f = CPU / (m * n),
m depending on the kind of sound, hence

    word = K / n,   K = CPU * 2.68435456 / m

    k  kind                       m
    0  pure tone                  2   (output toggles every n cycles)
    1  distortion C (poly4)       3   \\ period of poly4 sampled every n
    2                             5   |  cycles: 15 / gcd(n mod 15, 15);
    3                            15   /  n mod 15 = 0 -> silent
    4  poly5 tone                31
    5  poly17 noise               1   (VERA noise takes a new random value
    6  poly5 noise                2    once per period, POKEY noise can
                                       change every n cycles)

64 kHz 8 bit channels (n = 28 * (AUDF + 1)) are the usual case: their word
depends only on AUDF and on the kind, so it is read from a table:

    table kind 0 pure, 1 distortion C (via n mod 15), 2 poly5 tone,
               3 poly17 noise, 4 poly5 noise

Words above 65535 (above ~24.4 kHz) are clamped; 0 means silent.

Output (ca65), segment PSGTAB (page aligned):
    psgtab_lo, psgtab_hi : 10 pages each, (std * 5 + kind) * 256 + AUDF,
                           std 0 = PAL, 1 = NTSC
    psg_ktab             : K, 24 bit little endian, (std * 7 + k) * 3
"""
import math
import sys

CPU = {0: 1773447, 1: 1789773}          # PAL, NTSC machine clock (Hz)
SCALE = 2 ** 17 * 512 / 25e6           # VERA word per Hz
KM = [2, 3, 5, 15, 31, 1, 2]            # m for k = 0..6


def k_const(std, k):
    return round(CPU[std] * SCALE / KM[k])


def word(std, kind, audf):
    n = 28 * (audf + 1)
    if kind == 1:
        r = n % 15
        if r == 0:
            return 0
        m = 15 // math.gcd(r, 15)
    else:
        m = {0: 2, 2: 31, 3: 1, 4: 2}[kind]
    return min(65535, round(CPU[std] * SCALE / m / n))


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: mkpsgtab.py output.s")
    vals = [word(s, k, a) for s in (0, 1) for k in range(5) for a in range(256)]
    out = ["; generated by tools/mkpsgtab.py - do not edit",
           "; VERA PSG frequency words for POKEY 64 kHz 8 bit channels",
           "; (std * 5 + kind) * 256 + AUDF, std 0 = PAL, 1 = NTSC",
           "        .export psgtab_lo, psgtab_hi, psg_ktab",
           '        .segment "PSGTAB"',
           "psgtab_lo:"]
    for i in range(0, len(vals), 16):
        out.append("        .byte " + ",".join("$%02X" % (v & 0xFF) for v in vals[i:i + 16]))
    out.append("psgtab_hi:")
    for i in range(0, len(vals), 16):
        out.append("        .byte " + ",".join("$%02X" % (v >> 8) for v in vals[i:i + 16]))
    out.append('        .segment "RODATA"')
    out.append("; K = CPU * 2^17 * 512 / 25e6 / m, (std * 7 + k) * 3, 24 bit")
    out.append("psg_ktab:")
    for s in (0, 1):
        out.append("        .faraddr " + ", ".join(str(k_const(s, k)) for k in range(7)))
    with open(sys.argv[1], "w") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
